// GENERATED by research/export/eden_release.py from the WinR research repo (commit 0469020) on 2026-09-30.
// Do not edit by hand. Re-run the script so the engine, dashboard and app keep the research numbers.
import type { AmanRecord, HaorFlashFlood, LedgerCheckRow, PilotAdvisories, PilotConditions, RabiRecord, ReleaseInfo, SoilAndProductivity, SrdiCard } from './release_types.ts';

export const RELEASE: ReleaseInfo = {
  "id": "tanore-2026.09.30",
  "generatedOn": "2026-09-30",
  "researchCommit": "0469020",
  "generator": "research/export/eden_release.py (WinR research repo)",
  "pilot": "Talanda union, Tanore upazila, Rajshahi (research site RAJ_TANORE)",
  "seasons": "2001-2025"
};

export const TANORE_AMAN_REPLAY: Record<string, AmanRecord> = {
  "BRRI dhan71": {
    "variety": "BRRI dhan71",
    "durationDays": [
      114,
      117
    ],
    "seedbedWindow": [
      "07-05",
      "07-15"
    ],
    "transplant": "08-01",
    "flowering": "10-04",
    "maturity": "11-03",
    "fieldFree": "11-10",
    "rescueSeasons": 7,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2015,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 410,
    "floweringNightTempC": 25.1,
    "fieldDays": 94
  },
  "BRRI dhan87": {
    "variety": "BRRI dhan87",
    "durationDays": [
      125,
      128
    ],
    "seedbedWindow": [
      "06-15",
      "07-07"
    ],
    "transplant": "07-24",
    "flowering": "09-30",
    "maturity": "10-30",
    "fieldFree": "11-06",
    "rescueSeasons": 6,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 433,
    "floweringNightTempC": null,
    "fieldDays": 98
  },
  "BRRI dhan103": {
    "variety": "BRRI dhan103",
    "durationDays": [
      128,
      133
    ],
    "seedbedWindow": [
      "06-15",
      "07-07"
    ],
    "transplant": "07-24",
    "flowering": "10-04",
    "maturity": "11-03",
    "fieldFree": "11-10",
    "rescueSeasons": 7,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2015,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 448,
    "floweringNightTempC": null,
    "fieldDays": 102
  },
  "BRRI dhan49": {
    "variety": "BRRI dhan49",
    "durationDays": [
      135,
      135
    ],
    "seedbedWindow": [
      "06-15",
      "07-15"
    ],
    "transplant": "07-28",
    "flowering": "10-13",
    "maturity": "11-12",
    "fieldFree": "11-19",
    "rescueSeasons": 9,
    "totalSeasons": 25,
    "rescueYears": [
      2008,
      2010,
      2011,
      2013,
      2014,
      2015,
      2018,
      2021,
      2022
    ],
    "cropWaterUseMm": 460,
    "floweringNightTempC": 23.8,
    "fieldDays": 107
  },
  "BRRI dhan75": {
    "variety": "BRRI dhan75",
    "durationDays": [
      110,
      115
    ],
    "seedbedWindow": [
      "07-21",
      "08-20"
    ],
    "transplant": "08-28",
    "flowering": "10-26",
    "maturity": "11-25",
    "fieldFree": "12-02",
    "rescueSeasons": 20,
    "totalSeasons": 25,
    "rescueYears": [
      2001,
      2002,
      2004,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2015,
      2016,
      2018,
      2020,
      2021,
      2022,
      2023,
      2025
    ],
    "cropWaterUseMm": 357,
    "floweringNightTempC": null,
    "fieldDays": 89
  }
};

export const TANORE_RABI_REPLAY: Record<string, RabiRecord> = {
  "BARI Masur-8": {
    "key": "BARI Masur-8",
    "replayLabel": "Lentil (BARI Masur-8)",
    "sowing": "11-10",
    "harvest": "03-01",
    "sowingWindow": [
      "10-23",
      "11-14"
    ],
    "sowingWindowSource": "BARI handbook",
    "seasons": 24,
    "netIrrigationMm": 199,
    "netIrrigationRangeMm": [
      160,
      220
    ],
    "pumpedM3PerHa": 1995,
    "fieldDays": 112,
    "cropWaterUseMm": 267,
    "heat": null,
    "fertilizer": {
      "cropGroupBangla": "মসুর",
      "ureaKgHa": 54.3,
      "tspKgHa": 107.5,
      "mopKgHa": 36.0,
      "gypsumKgHa": 37.8,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 1.51
  },
  "BARI Sarisha-14": {
    "key": "BARI Sarisha-14",
    "replayLabel": "Mustard (BARI Sarisha-14)",
    "sowing": "11-10",
    "harvest": "01-28",
    "sowingWindow": [
      "10-15",
      "11-15"
    ],
    "sowingWindowSource": "BARI handbook",
    "seasons": 24,
    "netIrrigationMm": 114,
    "netIrrigationRangeMm": [
      92,
      135
    ],
    "pumpedM3PerHa": 1140,
    "fieldDays": 80,
    "cropWaterUseMm": 169,
    "heat": null,
    "fertilizer": {
      "cropGroupBangla": "সরিষা",
      "ureaKgHa": 229.0,
      "tspKgHa": 160.1,
      "mopKgHa": 101.0,
      "gypsumKgHa": 65.6,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 1.52
  },
  "BARI Gom 33 (Early)": {
    "key": "BARI Gom 33 (Early)",
    "replayLabel": "Wheat (BARI Gom 33), sown 20 Nov",
    "sowing": "11-20",
    "harvest": "03-04",
    "sowingWindow": [
      "11-15",
      "11-30"
    ],
    "sowingWindowSource": "BWMRI variety page",
    "seasons": 24,
    "netIrrigationMm": 198,
    "netIrrigationRangeMm": [
      150,
      219
    ],
    "pumpedM3PerHa": 1985,
    "fieldDays": 105,
    "cropWaterUseMm": 261,
    "heat": {
      "stage": "grain filling",
      "stageBangla": "দানা পুষ্ট হওয়ার সময়",
      "thresholdC": 30,
      "windowDays": 30,
      "hotDays": 12
    },
    "fertilizer": {
      "cropGroupBangla": "গম",
      "ureaKgHa": 305.0,
      "tspKgHa": 142.6,
      "mopKgHa": 151.1,
      "gypsumKgHa": 63.6,
      "zincSulphateKgHa": 8.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.09
  },
  "BARI Gom 33 (Late)": {
    "key": "BARI Gom 33 (Late)",
    "replayLabel": "Wheat (BARI Gom 33), sown 10 Dec",
    "sowing": "12-10",
    "harvest": "03-24",
    "sowingWindow": [
      "11-15",
      "11-30"
    ],
    "sowingWindowSource": "BWMRI variety page",
    "seasons": 24,
    "netIrrigationMm": 234,
    "netIrrigationRangeMm": [
      189,
      287
    ],
    "pumpedM3PerHa": 2345,
    "fieldDays": 105,
    "cropWaterUseMm": 315,
    "heat": {
      "stage": "grain filling",
      "stageBangla": "দানা পুষ্ট হওয়ার সময়",
      "thresholdC": 30,
      "windowDays": 30,
      "hotDays": 27
    },
    "fertilizer": {
      "cropGroupBangla": "গম",
      "ureaKgHa": 305.0,
      "tspKgHa": 142.6,
      "mopKgHa": 151.1,
      "gypsumKgHa": 63.6,
      "zincSulphateKgHa": 8.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.09
  },
  "BRRI dhan28": {
    "key": "BRRI dhan28",
    "replayLabel": "Boro (BRRI dhan28)",
    "sowing": "02-01",
    "harvest": "05-14",
    "sowingWindow": null,
    "sowingWindowSource": null,
    "seasons": 24,
    "netIrrigationMm": 797,
    "netIrrigationRangeMm": [
      688,
      896
    ],
    "pumpedM3PerHa": 7975,
    "fieldDays": 103,
    "cropWaterUseMm": 588,
    "heat": {
      "stage": "flowering",
      "stageBangla": "ফুল আসার সময়",
      "thresholdC": 35,
      "windowDays": 15,
      "hotDays": 12
    },
    "fertilizer": {
      "cropGroupBangla": "বোরো",
      "ureaKgHa": 365.8,
      "tspKgHa": 125.1,
      "mopKgHa": 91.0,
      "gypsumKgHa": 51.7,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.02
  }
};

export const TALANDA_SRDI: SrdiCard = {
  "siteId": "RAJ_TANORE",
  "unionBangla": "তালন্দ",
  "soilTypeBangla": "খিয়ার মাটি",
  "landTypeBangla": "মাঝারি উঁচু জমি",
  "aman": {
    "cropGroupBangla": "আমন রোপা",
    "ureaKgHa": 229.0,
    "tspKgHa": 90.0,
    "mopKgHa": 76.0,
    "gypsumKgHa": 53.0,
    "zincSulphateKgHa": 5.4,
    "boricAcidKgHa": 0.0
  },
  "source": "SRDI Fertilizer Recommendation System union card (frs.srdi.gov.bd)"
};

export const TANORE_CONDITIONS: PilotConditions = {
  "siteId": "RAJ_TANORE",
  "lat": 24.62,
  "lon": 88.56,
  "bmdStation": "41895 ShahMokhdum",
  "bmdStationKm": 21,
  "smap": {
    "date": "2026-09-23",
    "rootZoneM3M3": 0.311,
    "sameDatePastYears": [
      {
        "year": 2024,
        "rootZoneM3M3": 0.37
      },
      {
        "year": 2025,
        "rootZoneM3M3": 0.343
      }
    ],
    "nov10TypicalM3M3": 0.335,
    "nov10Years": [
      2023,
      2024,
      2025
    ]
  },
  "rainLast30Days": {
    "from": "2026-08-24",
    "to": "2026-09-22",
    "imergLateMm": 179.6,
    "lateFinalRatio": 0.68,
    "pctOfNormal": {
      "imergLate": 74,
      "imergAdjusted": 116,
      "merra2": 105
    },
    "verdict": "uncertain (estimates disagree)"
  },
  "rootZoneGldasMm": {
    "oct20": 312,
    "nov10": 290,
    "nov19": 285,
    "lostNov10To19": 7.9,
    "smapSpearman": 0.86
  },
  "groundwater": {
    "source": "GLDAS-2.2 groundwater (GRACE-assimilated)",
    "trendMmPerYear": -7.4,
    "changeMm": -147.0,
    "period": "2003-07 to 2021-25"
  },
  "winterGreenness": {
    "product": "MODIS MOD13Q1 NDVI, 250 m",
    "early": {
      "years": "2001-02 to 2005-06",
      "peakNdvi": 0.53,
      "cyclesPerYear": 1.8
    },
    "recent": {
      "years": "2020-21 to 2024-25",
      "peakNdvi": 0.82,
      "cyclesPerYear": 2.8
    }
  },
  "landUse": {
    "year": "2014-15",
    "croppingIntensityPct": 224.0,
    "topPattern": "Boro-Fallow-T. Aman",
    "topPatternPct": 33.0
  },
  "cattlePerKm2": 197.2
};

export const TANORE_ADVISORIES: PilotAdvisories = {
  "heatTrends": [
    {
      "measure": "boro_days_ge35",
      "mean1991to2005": 12.93,
      "mean2011to2025": 10.47,
      "trendPerDecade": -0.56,
      "kendallP": 0.074
    },
    {
      "measure": "boro_night_c",
      "mean1991to2005": 22.4,
      "mean2011to2025": 22.77,
      "trendPerDecade": 0.17,
      "kendallP": 0.196
    },
    {
      "measure": "aman49_night_c",
      "mean1991to2005": 23.76,
      "mean2011to2025": 24.05,
      "trendPerDecade": 0.15,
      "kendallP": 0.478
    },
    {
      "measure": "aman71_night_c",
      "mean1991to2005": 24.87,
      "mean2011to2025": 25.46,
      "trendPerDecade": 0.29,
      "kendallP": 0.015
    },
    {
      "measure": "wheat_20nov_days_gt30",
      "mean1991to2005": 16.07,
      "mean2011to2025": 8.87,
      "trendPerDecade": -4.29,
      "kendallP": 0.001
    },
    {
      "measure": "wheat_10dec_days_gt30",
      "mean1991to2005": 26.47,
      "mean2011to2025": 22.6,
      "trendPerDecade": -1.43,
      "kendallP": 0.061
    }
  ],
  "cattleHeat": [
    {
      "month": 1,
      "meanThi": 60.8,
      "dangerShare": 0.0,
      "emergencyShare": 0.0,
      "nightsWithoutReliefPct": 0.0,
      "coolestHours": [
        "04:00",
        "05:00",
        "06:00",
        "07:00"
      ]
    },
    {
      "month": 2,
      "meanThi": 65.8,
      "dangerShare": 0.0,
      "emergencyShare": 0.0,
      "nightsWithoutReliefPct": 0.0,
      "coolestHours": [
        "03:00",
        "04:00",
        "05:00",
        "06:00"
      ]
    },
    {
      "month": 3,
      "meanThi": 72.1,
      "dangerShare": 0.115,
      "emergencyShare": 0.0,
      "nightsWithoutReliefPct": 2.2,
      "coolestHours": [
        "03:00",
        "04:00",
        "05:00",
        "06:00"
      ]
    },
    {
      "month": 4,
      "meanThi": 77.6,
      "dangerShare": 0.414,
      "emergencyShare": 0.075,
      "nightsWithoutReliefPct": 54.4,
      "coolestHours": [
        "02:00",
        "03:00",
        "04:00",
        "05:00"
      ]
    },
    {
      "month": 5,
      "meanThi": 80.8,
      "dangerShare": 0.699,
      "emergencyShare": 0.198,
      "nightsWithoutReliefPct": 95.7,
      "coolestHours": [
        "02:00",
        "03:00",
        "04:00",
        "05:00"
      ]
    },
    {
      "month": 6,
      "meanThi": 82.9,
      "dangerShare": 0.958,
      "emergencyShare": 0.35,
      "nightsWithoutReliefPct": 100.0,
      "coolestHours": [
        "02:00",
        "03:00",
        "04:00",
        "05:00"
      ]
    },
    {
      "month": 7,
      "meanThi": 82.6,
      "dangerShare": 0.964,
      "emergencyShare": 0.333,
      "nightsWithoutReliefPct": 100.0,
      "coolestHours": [
        "02:00",
        "03:00",
        "04:00",
        "05:00"
      ]
    },
    {
      "month": 8,
      "meanThi": 81.5,
      "dangerShare": 0.855,
      "emergencyShare": 0.164,
      "nightsWithoutReliefPct": 100.0,
      "coolestHours": [
        "02:00",
        "03:00",
        "04:00",
        "05:00"
      ]
    },
    {
      "month": 9,
      "meanThi": 81.4,
      "dangerShare": 0.833,
      "emergencyShare": 0.161,
      "nightsWithoutReliefPct": 100.0,
      "coolestHours": [
        "03:00",
        "04:00",
        "05:00",
        "06:00"
      ]
    },
    {
      "month": 10,
      "meanThi": 77.6,
      "dangerShare": 0.411,
      "emergencyShare": 0.01,
      "nightsWithoutReliefPct": 63.4,
      "coolestHours": [
        "03:00",
        "04:00",
        "05:00",
        "06:00"
      ]
    },
    {
      "month": 11,
      "meanThi": 69.4,
      "dangerShare": 0.025,
      "emergencyShare": 0.0,
      "nightsWithoutReliefPct": 1.1,
      "coolestHours": [
        "03:00",
        "04:00",
        "05:00",
        "06:00"
      ]
    },
    {
      "month": 12,
      "meanThi": 62.0,
      "dangerShare": 0.0,
      "emergencyShare": 0.0,
      "nightsWithoutReliefPct": 0.0,
      "coolestHours": [
        "04:00",
        "05:00",
        "06:00",
        "07:00"
      ]
    }
  ],
  "cattleSource": "NASA POWER hourly temperature and humidity 2023-2025, THI (NRC 1971); explore/cattle_heat.py"
};

export const HAOR_FLASH_FLOOD: HaorFlashFlood = {
  "window": [
    "03-15",
    "05-15"
  ],
  "sohra": {
    "lat": 25.27,
    "lon": 91.73
  },
  "dharmapasha": {
    "lat": 24.89,
    "lon": 91.0
  },
  "watchMm": 200,
  "warningMm": 250,
  "source": "GPM IMERG daily rain at Sohra (Meghalaya), 3-day totals 15 Mar-15 May; flood years from FFWC annual reports",
  "seasons": [
    {
      "year": 2001,
      "sohraMax3Mm": 112.2,
      "sohraMax3End": "2001-04-29",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2002,
      "sohraMax3Mm": 125.1,
      "sohraMax3End": "2002-04-21",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2003,
      "sohraMax3Mm": 64.6,
      "sohraMax3End": "2003-03-30",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2004,
      "sohraMax3Mm": 382.1,
      "sohraMax3End": "2004-05-13",
      "label": "flood",
      "first200mm": "2004-04-15"
    },
    {
      "year": 2005,
      "sohraMax3Mm": 213.8,
      "sohraMax3End": "2005-03-21",
      "label": "unlabelled",
      "first200mm": "2005-03-21"
    },
    {
      "year": 2006,
      "sohraMax3Mm": 110.8,
      "sohraMax3End": "2006-04-04",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2007,
      "sohraMax3Mm": 206.9,
      "sohraMax3End": "2007-04-09",
      "label": "unlabelled",
      "first200mm": "2007-04-09"
    },
    {
      "year": 2008,
      "sohraMax3Mm": 107.0,
      "sohraMax3End": "2008-03-30",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2009,
      "sohraMax3Mm": 180.5,
      "sohraMax3End": "2009-05-02",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2010,
      "sohraMax3Mm": 288.6,
      "sohraMax3End": "2010-04-23",
      "label": "flood",
      "first200mm": "2010-04-21"
    },
    {
      "year": 2011,
      "sohraMax3Mm": 180.0,
      "sohraMax3End": "2011-03-21",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2012,
      "sohraMax3Mm": 208.7,
      "sohraMax3End": "2012-04-06",
      "label": "unlabelled",
      "first200mm": "2012-04-06"
    },
    {
      "year": 2013,
      "sohraMax3Mm": 340.3,
      "sohraMax3End": "2013-05-03",
      "label": "unlabelled",
      "first200mm": "2013-05-02"
    },
    {
      "year": 2014,
      "sohraMax3Mm": 170.2,
      "sohraMax3End": "2014-05-14",
      "label": "no flood",
      "first200mm": null
    },
    {
      "year": 2015,
      "sohraMax3Mm": 104.9,
      "sohraMax3End": "2015-04-04",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2016,
      "sohraMax3Mm": 165.6,
      "sohraMax3End": "2016-04-23",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2017,
      "sohraMax3Mm": 317.1,
      "sohraMax3End": "2017-04-03",
      "label": "flood",
      "first200mm": "2017-04-01"
    },
    {
      "year": 2018,
      "sohraMax3Mm": 125.8,
      "sohraMax3End": "2018-05-11",
      "label": "flood",
      "first200mm": null
    },
    {
      "year": 2019,
      "sohraMax3Mm": 101.0,
      "sohraMax3End": "2019-05-14",
      "label": "flood",
      "first200mm": null
    },
    {
      "year": 2020,
      "sohraMax3Mm": 83.1,
      "sohraMax3End": "2020-04-18",
      "label": "no flood",
      "first200mm": null
    },
    {
      "year": 2021,
      "sohraMax3Mm": 67.3,
      "sohraMax3End": "2021-04-16",
      "label": "no flood",
      "first200mm": null
    },
    {
      "year": 2022,
      "sohraMax3Mm": 341.9,
      "sohraMax3End": "2022-05-15",
      "label": "unlabelled",
      "first200mm": "2022-05-15"
    },
    {
      "year": 2023,
      "sohraMax3Mm": 90.9,
      "sohraMax3End": "2023-03-21",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2024,
      "sohraMax3Mm": 121.6,
      "sohraMax3End": "2024-05-06",
      "label": "unlabelled",
      "first200mm": null
    },
    {
      "year": 2025,
      "sohraMax3Mm": 189.2,
      "sohraMax3End": "2025-04-24",
      "label": "unlabelled",
      "first200mm": null
    }
  ],
  "skill": [
    {
      "thresholdMm": 100,
      "floodYearsCaught": "5 of 5",
      "noFloodYearsFlagged": "1 of 3",
      "seasonsFlagged": "21 of 25"
    },
    {
      "thresholdMm": 150,
      "floodYearsCaught": "3 of 5",
      "noFloodYearsFlagged": "1 of 3",
      "seasonsFlagged": "13 of 25"
    },
    {
      "thresholdMm": 200,
      "floodYearsCaught": "3 of 5",
      "noFloodYearsFlagged": "0 of 3",
      "seasonsFlagged": "8 of 25"
    },
    {
      "thresholdMm": 250,
      "floodYearsCaught": "3 of 5",
      "noFloodYearsFlagged": "0 of 3",
      "seasonsFlagged": "5 of 25"
    }
  ],
  "escape": [
    {
      "variety": "BRRI dhan88",
      "sowing": "BRRI calendar",
      "medianHarvest": "13 Apr",
      "burstsBeforeHarvest": 1,
      "bursts": 5,
      "caughtYears": [
        2017
      ]
    },
    {
      "variety": "BRRI dhan88",
      "sowing": "two weeks early",
      "medianHarvest": "30 Mar",
      "burstsBeforeHarvest": 0,
      "bursts": 5,
      "caughtYears": []
    },
    {
      "variety": "BRRI dhan81",
      "sowing": "BRRI calendar",
      "medianHarvest": "13 Apr",
      "burstsBeforeHarvest": 1,
      "bursts": 5,
      "caughtYears": [
        2017
      ]
    },
    {
      "variety": "BRRI dhan81",
      "sowing": "two weeks early",
      "medianHarvest": "30 Mar",
      "burstsBeforeHarvest": 0,
      "bursts": 5,
      "caughtYears": []
    },
    {
      "variety": "BRRI dhan29",
      "sowing": "BRRI calendar",
      "medianHarvest": "16 Apr",
      "burstsBeforeHarvest": 1,
      "bursts": 5,
      "caughtYears": [
        2017
      ]
    },
    {
      "variety": "BRRI dhan29",
      "sowing": "two weeks early",
      "medianHarvest": "02 Apr",
      "burstsBeforeHarvest": 0,
      "bursts": 5,
      "caughtYears": []
    },
    {
      "variety": "BRRI dhan28",
      "sowing": "BRRI calendar",
      "medianHarvest": "14 May",
      "burstsBeforeHarvest": 4,
      "bursts": 5,
      "caughtYears": [
        2004,
        2010,
        2013,
        2017
      ]
    },
    {
      "variety": "BRRI dhan28",
      "sowing": "two weeks early",
      "medianHarvest": "30 Apr",
      "burstsBeforeHarvest": 3,
      "bursts": 5,
      "caughtYears": [
        2004,
        2010,
        2017
      ]
    },
    {
      "variety": "BRRI dhan89",
      "sowing": "BRRI calendar",
      "medianHarvest": "13 Apr",
      "burstsBeforeHarvest": 1,
      "bursts": 5,
      "caughtYears": [
        2017
      ]
    },
    {
      "variety": "BRRI dhan89",
      "sowing": "two weeks early",
      "medianHarvest": "30 Mar",
      "burstsBeforeHarvest": 0,
      "bursts": 5,
      "caughtYears": []
    },
    {
      "variety": "BRRI dhan92",
      "sowing": "BRRI calendar",
      "medianHarvest": "15 Apr",
      "burstsBeforeHarvest": 1,
      "bursts": 5,
      "caughtYears": [
        2017
      ]
    },
    {
      "variety": "BRRI dhan92",
      "sowing": "two weeks early",
      "medianHarvest": "01 Apr",
      "burstsBeforeHarvest": 0,
      "bursts": 5,
      "caughtYears": []
    }
  ]
};

export const TANORE_SOIL_CARBON: SoilAndProductivity = {
  "soilCarbonGm2": 4684,
  "soilCarbonTrendGm2PerYear": 76.2,
  "dryDaysVsAmanGppRho": 0.26,
  "dryDaysVsAmanGppSeasons": 11,
  "monsoonRainVsAmanGppRho": -0.56,
  "source": "SMAP L4 carbon (SPL4CMDL) GPP and soil organic carbon, 2015-2025"
};

export const TANORE_LEDGER_RESEARCH: LedgerCheckRow[] = [
  {
    "rotation": "BRRI dhan49 then Boro (BRRI dhan28)",
    "pumpedM3PerHa": 7975,
    "floodedRiceDays": 182,
    "ureaKgHa": 595,
    "bareDays": 155
  },
  {
    "rotation": "BRRI dhan49 then wheat, sown 20 Nov",
    "pumpedM3PerHa": 1985,
    "floodedRiceDays": 93,
    "ureaKgHa": 534,
    "bareDays": 153
  },
  {
    "rotation": "BRRI dhan71 then lentil",
    "pumpedM3PerHa": 1995,
    "floodedRiceDays": 80,
    "ureaKgHa": 283,
    "bareDays": 159
  },
  {
    "rotation": "BRRI dhan71 then mustard",
    "pumpedM3PerHa": 1140,
    "floodedRiceDays": 80,
    "ureaKgHa": 458,
    "bareDays": 191
  }
];
