// GENERATED by research/export/eden_release.py from the WinR research repo (commit 2a3c406) on 2026-09-29.
// Do not edit by hand. Re-run the script so the engine, dashboard and app keep the research numbers.
import type { AmanRecord, PilotConditions, RabiRecord, ReleaseInfo, SrdiCard } from './release_types.ts';

export const RELEASE: ReleaseInfo = {
  "id": "tanore-2026.09.29",
  "generatedOn": "2026-09-29",
  "researchCommit": "2a3c406",
  "generator": "research/export/eden_release.py (WinR research repo)",
  "pilot": "Talanda union, Tanore upazila, Rajshahi (research site RAJ_TANORE)",
  "seasons": "2001-2025"
};

export const TANORE_AMAN_REPLAY: Record<string, AmanRecord> = {
  "BRRI dhan71": {
    "variety": "BRRI dhan71",
    "durationDays": [
      114,
      117
    ],
    "seedbedWindow": [
      "07-05",
      "07-15"
    ],
    "transplant": "08-01",
    "flowering": "10-04",
    "maturity": "11-03",
    "fieldFree": "11-10",
    "rescueSeasons": 7,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2015,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 410,
    "floweringNightTempC": 25.1
  },
  "BRRI dhan87": {
    "variety": "BRRI dhan87",
    "durationDays": [
      125,
      128
    ],
    "seedbedWindow": [
      "06-15",
      "07-07"
    ],
    "transplant": "07-24",
    "flowering": "09-30",
    "maturity": "10-30",
    "fieldFree": "11-06",
    "rescueSeasons": 6,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 433,
    "floweringNightTempC": null
  },
  "BRRI dhan103": {
    "variety": "BRRI dhan103",
    "durationDays": [
      128,
      133
    ],
    "seedbedWindow": [
      "06-15",
      "07-07"
    ],
    "transplant": "07-24",
    "flowering": "10-04",
    "maturity": "11-03",
    "fieldFree": "11-10",
    "rescueSeasons": 7,
    "totalSeasons": 25,
    "rescueYears": [
      2003,
      2010,
      2011,
      2015,
      2018,
      2019,
      2021
    ],
    "cropWaterUseMm": 448,
    "floweringNightTempC": null
  },
  "BRRI dhan49": {
    "variety": "BRRI dhan49",
    "durationDays": [
      135,
      135
    ],
    "seedbedWindow": [
      "06-15",
      "07-15"
    ],
    "transplant": "07-28",
    "flowering": "10-13",
    "maturity": "11-12",
    "fieldFree": "11-19",
    "rescueSeasons": 9,
    "totalSeasons": 25,
    "rescueYears": [
      2008,
      2010,
      2011,
      2013,
      2014,
      2015,
      2018,
      2021,
      2022
    ],
    "cropWaterUseMm": 460,
    "floweringNightTempC": 23.8
  },
  "BRRI dhan75": {
    "variety": "BRRI dhan75",
    "durationDays": [
      110,
      115
    ],
    "seedbedWindow": [
      "07-21",
      "08-20"
    ],
    "transplant": "08-28",
    "flowering": "10-26",
    "maturity": "11-25",
    "fieldFree": "12-02",
    "rescueSeasons": 20,
    "totalSeasons": 25,
    "rescueYears": [
      2001,
      2002,
      2004,
      2006,
      2007,
      2008,
      2009,
      2010,
      2011,
      2012,
      2013,
      2014,
      2015,
      2016,
      2018,
      2020,
      2021,
      2022,
      2023,
      2025
    ],
    "cropWaterUseMm": 357,
    "floweringNightTempC": null
  }
};

export const TANORE_RABI_REPLAY: Record<string, RabiRecord> = {
  "BARI Masur-8": {
    "key": "BARI Masur-8",
    "replayLabel": "Lentil (BARI Masur-8)",
    "sowing": "11-10",
    "harvest": "03-01",
    "sowingWindow": [
      "10-23",
      "11-14"
    ],
    "sowingWindowSource": "BARI handbook",
    "seasons": 24,
    "netIrrigationMm": 199,
    "netIrrigationRangeMm": [
      160,
      220
    ],
    "cropWaterUseMm": 267,
    "heat": null,
    "fertilizer": {
      "cropGroupBangla": "মসুর",
      "ureaKgHa": 54.3,
      "tspKgHa": 107.5,
      "mopKgHa": 36.0,
      "gypsumKgHa": 37.8,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 1.51
  },
  "BARI Sarisha-14": {
    "key": "BARI Sarisha-14",
    "replayLabel": "Mustard (BARI Sarisha-14)",
    "sowing": "11-10",
    "harvest": "01-28",
    "sowingWindow": [
      "10-15",
      "11-15"
    ],
    "sowingWindowSource": "BARI handbook",
    "seasons": 24,
    "netIrrigationMm": 114,
    "netIrrigationRangeMm": [
      92,
      135
    ],
    "cropWaterUseMm": 169,
    "heat": null,
    "fertilizer": {
      "cropGroupBangla": "সরিষা",
      "ureaKgHa": 229.0,
      "tspKgHa": 160.1,
      "mopKgHa": 101.0,
      "gypsumKgHa": 65.6,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 1.52
  },
  "BARI Gom 33 (Early)": {
    "key": "BARI Gom 33 (Early)",
    "replayLabel": "Wheat (BARI Gom 33), sown 20 Nov",
    "sowing": "11-20",
    "harvest": "03-04",
    "sowingWindow": [
      "11-15",
      "11-30"
    ],
    "sowingWindowSource": "BWMRI variety page",
    "seasons": 24,
    "netIrrigationMm": 198,
    "netIrrigationRangeMm": [
      150,
      219
    ],
    "cropWaterUseMm": 261,
    "heat": {
      "stage": "grain filling",
      "stageBangla": "দানা পুষ্ট হওয়ার সময়",
      "thresholdC": 30,
      "windowDays": 30,
      "hotDays": 12
    },
    "fertilizer": {
      "cropGroupBangla": "গম",
      "ureaKgHa": 305.0,
      "tspKgHa": 142.6,
      "mopKgHa": 151.1,
      "gypsumKgHa": 63.6,
      "zincSulphateKgHa": 8.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.09
  },
  "BARI Gom 33 (Late)": {
    "key": "BARI Gom 33 (Late)",
    "replayLabel": "Wheat (BARI Gom 33), sown 10 Dec",
    "sowing": "12-10",
    "harvest": "03-24",
    "sowingWindow": [
      "11-15",
      "11-30"
    ],
    "sowingWindowSource": "BWMRI variety page",
    "seasons": 24,
    "netIrrigationMm": 234,
    "netIrrigationRangeMm": [
      189,
      287
    ],
    "cropWaterUseMm": 315,
    "heat": {
      "stage": "grain filling",
      "stageBangla": "দানা পুষ্ট হওয়ার সময়",
      "thresholdC": 30,
      "windowDays": 30,
      "hotDays": 27
    },
    "fertilizer": {
      "cropGroupBangla": "গম",
      "ureaKgHa": 305.0,
      "tspKgHa": 142.6,
      "mopKgHa": 151.1,
      "gypsumKgHa": 63.6,
      "zincSulphateKgHa": 8.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.09
  },
  "BRRI dhan28": {
    "key": "BRRI dhan28",
    "replayLabel": "Boro (BRRI dhan28)",
    "sowing": "02-01",
    "harvest": "05-14",
    "sowingWindow": null,
    "sowingWindowSource": null,
    "seasons": 24,
    "netIrrigationMm": 797,
    "netIrrigationRangeMm": [
      688,
      896
    ],
    "cropWaterUseMm": 588,
    "heat": {
      "stage": "flowering",
      "stageBangla": "ফুল আসার সময়",
      "thresholdC": 35,
      "windowDays": 15,
      "hotDays": 12
    },
    "fertilizer": {
      "cropGroupBangla": "বোরো",
      "ureaKgHa": 365.8,
      "tspKgHa": 125.1,
      "mopKgHa": 91.0,
      "gypsumKgHa": 51.7,
      "zincSulphateKgHa": 6.7,
      "boricAcidKgHa": 0.0
    },
    "districtYieldTPerHa": 4.02
  }
};

export const TALANDA_SRDI: SrdiCard = {
  "siteId": "RAJ_TANORE",
  "unionBangla": "তালন্দ",
  "soilTypeBangla": "খিয়ার মাটি",
  "landTypeBangla": "মাঝারি উঁচু জমি",
  "aman": {
    "cropGroupBangla": "আমন রোপা",
    "ureaKgHa": 229.0,
    "tspKgHa": 90.0,
    "mopKgHa": 76.0,
    "gypsumKgHa": 53.0,
    "zincSulphateKgHa": 5.4,
    "boricAcidKgHa": 0.0
  },
  "source": "SRDI Fertilizer Recommendation System union card (frs.srdi.gov.bd)"
};

export const TANORE_CONDITIONS: PilotConditions = {
  "siteId": "RAJ_TANORE",
  "lat": 24.62,
  "lon": 88.56,
  "bmdStation": "41895 ShahMokhdum",
  "bmdStationKm": 21,
  "smap": {
    "date": "2026-09-23",
    "rootZoneM3M3": 0.311,
    "sameDatePastYears": [
      {
        "year": 2024,
        "rootZoneM3M3": 0.37
      },
      {
        "year": 2025,
        "rootZoneM3M3": 0.343
      }
    ],
    "nov10TypicalM3M3": 0.335,
    "nov10Years": [
      2023,
      2024,
      2025
    ]
  },
  "rainLast30Days": {
    "from": "2026-08-24",
    "to": "2026-09-22",
    "imergLateMm": 179.6,
    "lateFinalRatio": 0.68,
    "pctOfNormal": {
      "imergLate": 74,
      "imergAdjusted": 116,
      "merra2": 105
    },
    "verdict": "uncertain (estimates disagree)"
  },
  "rootZoneGldasMm": {
    "oct20": 312,
    "nov10": 290,
    "nov19": 285,
    "lostNov10To19": 7.9,
    "smapSpearman": 0.86
  },
  "groundwater": {
    "source": "GLDAS-2.2 groundwater (GRACE-assimilated)",
    "trendMmPerYear": -7.4,
    "changeMm": -147.0,
    "period": "2003-07 to 2021-25"
  },
  "winterGreenness": {
    "product": "MODIS MOD13Q1 NDVI, 250 m",
    "early": {
      "years": "2001-02 to 2005-06",
      "peakNdvi": 0.53,
      "cyclesPerYear": 1.8
    },
    "recent": {
      "years": "2020-21 to 2024-25",
      "peakNdvi": 0.82,
      "cyclesPerYear": 2.8
    }
  },
  "landUse": {
    "year": "2014-15",
    "croppingIntensityPct": 224.0,
    "topPattern": "Boro-Fallow-T. Aman",
    "topPatternPct": 33.0
  },
  "cattlePerKm2": 197.2
};
